// scripts/mercury-maps/build.mjs — USGS MESSENGER rasters → web textures.
//
// One-off, NOT runtime. Downloads ~1.3 GB into .cache/usgs (skipped if present),
// box-downsamples by exact integer factors, encodes WebP, writes
// src/terminal/mercury/planet/mercuryMaps.generated.js. Re-run to regenerate.
// Data: NASA/JHUAPL/Carnegie MESSENGER MDIS; USGS Astrogeology. Public domain.
//
//   node scripts/mercury-maps/build.mjs

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { pipeline } from 'node:stream/promises';
import { Readable } from 'node:stream';
import { fromFile } from 'geotiff';
import sharp from 'sharp';
import { boxDownsample, rollToLonZero, quantise8Dithered, minMax } from './lib.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const CACHE = path.join(ROOT, '.cache', 'usgs');
const OUT = path.join(ROOT, 'public', 'mercury');
const GEN = path.join(ROOT, 'src', 'terminal', 'mercury', 'planet', 'mercuryMaps.generated.js');

const SRC = {
  albedo: 'https://planetarymaps.usgs.gov/mosaic/Mercury_MESSENGER_MDIS_Basemap_EnhancedColor_Mosaic_Global_665m.tif',
  dem: 'https://planetarymaps.usgs.gov/mosaic/Mercury_Messenger_USGS_DEM_Global_665m_v2.tif',
};
const DATUM_M = 2439400;
const ALBEDO_QUALITY = 84; // stepped down from 88 to fit BUDGET.desktop
const BUDGET = { desktop: 4.5e6, mobile: 1.5e6 };
// Exact integer factors of 23040×11520.
const SIZES = {
  desktop: { albedoF: 5, demF: 10 },  // albedo 4608×2304, dem 2304×1152
  mobile:  { albedoF: 10, demF: 20 }, // albedo 2304×1152, dem 1152×576
};

async function download(url) {
  fs.mkdirSync(CACHE, { recursive: true });
  const file = path.join(CACHE, path.basename(url));
  if (fs.existsSync(file)) return file;
  console.log(`downloading ${url}`);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  await pipeline(Readable.fromWeb(res.body), fs.createWriteStream(file + '.part'));
  fs.renameSync(file + '.part', file);
  return file;
}

async function readRaster(file) {
  const tiff = await fromFile(file);
  const img = await tiff.getImage();
  const w = img.getWidth(), h = img.getHeight(), channels = img.getSamplesPerPixel();
  const [x0] = img.getBoundingBox(); // metres on the datum sphere
  const lonStartDeg = (x0 / DATUM_M) * (180 / Math.PI);
  const data = await img.readRasters({ interleave: true });
  console.log(`${path.basename(file)}: ${w}×${h}×${channels}, lon start ${lonStartDeg.toFixed(3)}°`);
  return { w, h, channels, data: rollToLonZero(data, w, h, channels, lonStartDeg) };
}

const toU8 = (f32) => Uint8Array.from(f32, (v) => Math.max(0, Math.min(255, Math.round(v))));

async function main() {
  fs.mkdirSync(OUT, { recursive: true });
  const albedo = await readRaster(await download(SRC.albedo));
  const dem = await readRaster(await download(SRC.dem));
  if (albedo.channels < 3) throw new Error('enhanced colour mosaic must have 3 bands');

  const NODATA = (v) => v > -20000 && v < 20000;
  for (let i = 0; i < dem.data.length; i++) if (!NODATA(dem.data[i])) dem.data[i] = 0;
  const { min, max } = minMax(dem.data);
  console.log(`DEM range ${min} … ${max} m`);

  const manifest = {};
  for (const [tier, { albedoF, demF }] of Object.entries(SIZES)) {
    const aw = albedo.w / albedoF, ah = albedo.h / albedoF;
    const dw = dem.w / demF, dh = dem.h / demF;
    const rgb = toU8(boxDownsample(albedo.data, albedo.w, albedo.h, albedo.channels, albedoF));
    const rgb3 = albedo.channels === 3 ? rgb : Uint8Array.from({ length: aw * ah * 3 }, (_, i) => rgb[Math.floor(i / 3) * albedo.channels + (i % 3)]);
    const albedoName = `albedo-${aw}.webp`;
    await sharp(Buffer.from(rgb3), { raw: { width: aw, height: ah, channels: 3 }, limitInputPixels: false })
      .webp({ quality: ALBEDO_QUALITY, effort: 6 }).toFile(path.join(OUT, albedoName));

    const h8 = quantise8Dithered(boxDownsample(dem.data, dem.w, dem.h, 1, demF), min, max);
    const demName = `dem-${dw}.webp`;
    await sharp(Buffer.from(h8), { raw: { width: dw, height: dh, channels: 1 }, limitInputPixels: false })
      .webp({ lossless: true, effort: 6 }).toFile(path.join(OUT, demName));

    const bytes = fs.statSync(path.join(OUT, albedoName)).size + fs.statSync(path.join(OUT, demName)).size;
    console.log(`${tier}: ${albedoName} + ${demName} = ${(bytes / 1e6).toFixed(2)} MB`);
    if (bytes > BUDGET[tier]) throw new Error(`${tier} maps ${bytes} B exceed budget ${BUDGET[tier]} B`);
    manifest[tier] = { albedo: `/mercury/${albedoName}`, dem: `/mercury/${demName}`, demSize: [dw, dh] };
  }

  fs.writeFileSync(GEN, `// GENERATED by scripts/mercury-maps/build.mjs — do not edit by hand.
// Source: MESSENGER MDIS enhanced-colour mosaic + USGS global DEM 665 m (public domain).

export const DEM_MIN_M = ${min};
export const DEM_MAX_M = ${max};

export const MAPS = ${JSON.stringify(manifest, null, 2)};
`);
  console.log(`wrote ${path.relative(ROOT, GEN)}`);
}

main().catch((err) => { console.error(err); process.exit(1); });
