// src/terminal/mercury/nebulaBake.js — renders the neutral nebula generator (planet/nebulaSky.js) once into a
// half-float, mipmapped cube map. The mips are what a rougher mirror samples (aetherSky.skyNeutral, NEBULA_MAX_LOD).
import * as THREE from 'three';
import { NEBULA_FACE, NEBULA_BAKE_VS, NEBULA_BAKE_FS } from './planet/nebulaSky';

// A half-float colour attachment needs one of these on WebGL2; without it the switch stays on the studio.
export function canBakeNebula(renderer) {
  const ctx = renderer.getContext();
  return !!(ctx.getExtension('EXT_color_buffer_half_float') || ctx.getExtension('EXT_color_buffer_float'));
}

export function bakeNebula(renderer) {
  const rt = new THREE.WebGLCubeRenderTarget(NEBULA_FACE, {
    type: THREE.HalfFloatType,
    generateMipmaps: true,
    minFilter: THREE.LinearMipmapLinearFilter,
    magFilter: THREE.LinearFilter,
    depthBuffer: false,
  });
  const geo = new THREE.SphereGeometry(1, 64, 32);
  const mat = new THREE.RawShaderMaterial({
    glslVersion: THREE.GLSL3, vertexShader: NEBULA_BAKE_VS, fragmentShader: NEBULA_BAKE_FS,
    side: THREE.BackSide, depthTest: false, depthWrite: false,
  });
  const scene = new THREE.Scene();
  scene.add(new THREE.Mesh(geo, mat));
  const cam = new THREE.CubeCamera(0.1, 10, rt);
  cam.update(renderer, scene); // restores the renderer's previous target; mips are generated by the last face's render
  geo.dispose();
  mat.dispose();
  return { texture: rt.texture, dispose: () => rt.dispose() };
}
