#!/usr/bin/env node
/**
 * soma-cli.js — Level 19: The Architect's Scaffold
 *
 * Interactive CLI for scaffolding new kernel files.
 * Asks for: Title, Content Type (markdown | rust), Tags.
 * Generates a file with a cryptographically unique ID, correct date,
 * and formatted boilerplate in the appropriate content directory.
 *
 * Usage (via package.json):
 *   npm run kernel:new
 *
 * Or direct:
 *   node scripts/soma-cli.js
 *   node scripts/soma-cli.js --type rust   # skip type prompt
 */

import fs       from 'fs';
import path     from 'path';
import readline from 'readline';
import { randomBytes } from 'crypto';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT      = path.join(__dirname, '..');

// ─── HELPERS ──────────────────────────────────────────────────────────────────

const rl = readline.createInterface({
  input:  process.stdin,
  output: process.stdout,
});

const ask = (prompt) => new Promise(resolve => rl.question(prompt, resolve));

/** Slugify a title: lowercase, word-chars only, underscores. */
function slugify(title) {
  return title.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '');
}

/** Build a display prefix from the first word(s) of the title. */
function idPrefix(title) {
  const words = title.trim().split(/\s+/);
  if (words.length === 1) return words[0].slice(0, 6).toUpperCase();
  return words.slice(0, 3).map(w => w[0]?.toUpperCase() || '').join('');
}

/**
 * Generate a mathematically secure ID.
 * Format: {PREFIX}-{YYYYMMDD}-{6 crypto hex chars}
 * e.g.   GKS-20260307-a3f9c2
 * Collision probability over 10M IDs: < 10^-9 (birthday bound on 2^24 space).
 */
function secureId(title) {
  const prefix  = idPrefix(title);
  const date    = new Date().toISOString().slice(0, 10).replace(/-/g, '');
  const entropy = randomBytes(3).toString('hex');
  return `${prefix}-${date}-${entropy}`;
}

// ─── BOILERPLATE GENERATORS ───────────────────────────────────────────────────

function markdownTemplate({ id, title, status, type, date, tags }) {
  const tagsYaml = tags.length ? `[${tags.join(', ')}]` : '[]';
  return `---
id: ${id}
title: ${title.toUpperCase()}
subtitle:
status: ${status}
type: ${type}
date: ${date}
tags: ${tagsYaml}
---

# ${title.toUpperCase()}
## scale94 // ${date}

---

> *""*

## 1.0 ABSTRACT



## 2.0 CORE PROTOCOL



## 3.0 OPERATIONAL DIRECTIVE



## 4.0 SYSTEM NOTES



---

\`\`\`
INITIATING: scale94 ${title} v1.0
STATUS:     ${status}
ID:         ${id}
\`\`\`

---

*scale94.com // scale@node*
*Kernel authored: ${date}*
`;
}

function rustTemplate({ id, date, tags, structName }) {
  const tagsComment = tags.length ? tags.join(', ') : 'Rust';
  return `// ${structName}.rs — Scale 9.4 Rust Kernel
// Generated by: soma-cli.js — Level 19: Architect's Scaffold
// ID:   ${id}
// Date: ${date}
// Tags: ${tagsComment}
//
// ADD THIS TO content/rust_kernels/src/lib.rs:
//   mod ${structName.toLowerCase()};
//   pub use ${structName.toLowerCase()}::${structName};

use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub struct ${structName} {
    // TODO: add kernel state fields
}

#[wasm_bindgen]
impl ${structName} {
    #[wasm_bindgen(constructor)]
    pub fn new() -> ${structName} {
        ${structName} {}
    }

    /// Static boot diagnostic — called by the terminal "run" command.
    /// Returns a HarmonicResult / kernel status string for the system log.
    pub fn boot() -> String {
        format!(
            "${id} // BOOT_OK\\nSTATUS: ONLINE\\nDATE: ${date}\\nSOURCE: content/rust_kernels/src/${structName.toLowerCase()}.rs"
        )
    }
}
`;
}

// ─── MAIN ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log('\n╔═══════════════════════════════════════════╗');
  console.log('║  SOMA CLI — LEVEL 19: ARCHITECT SCAFFOLD  ║');
  console.log('╚═══════════════════════════════════════════╝\n');

  const now = new Date();
  const date = now.toISOString().slice(0, 10);

  // ── Prompts ────────────────────────────────────────────────────────────────
  const titleRaw = (await ask('  > TITLE: ')).trim();
  if (!titleRaw) {
    console.error('\n  ✗ Title cannot be empty.\n');
    rl.close();
    process.exit(1);
  }

  // Pre-fill type from CLI flag if provided
  let typePrefill = '';
  const typeFlag = process.argv.indexOf('--type');
  if (typeFlag !== -1 && process.argv[typeFlag + 1]) {
    typePrefill = process.argv[typeFlag + 1].toLowerCase();
  }

  let typeAnswer;
  if (typePrefill === 'rust' || typePrefill === 'markdown' || typePrefill === 'md') {
    typeAnswer = typePrefill;
    console.log(`  > CONTENT TYPE [markdown/rust]: ${typeAnswer}  (from --type flag)`);
  } else {
    typeAnswer = (await ask('  > CONTENT TYPE [markdown/rust]: ')).trim().toLowerCase();
  }

  const isRust = typeAnswer === 'rust' || typeAnswer === 'rs';

  const tagsRaw  = (await ask('  > TAGS (comma-separated, or Enter to skip): ')).trim();
  const tags     = tagsRaw
    ? tagsRaw.split(',').map(t => t.trim()).filter(Boolean)
    : [titleRaw.split(' ')[0]];

  rl.close();

  // ── Generate ID + paths ───────────────────────────────────────────────────
  const id         = secureId(titleRaw);
  const slug       = slugify(titleRaw);
  const structName = titleRaw.split(/\s+/).map(w => w[0]?.toUpperCase() + w.slice(1).toLowerCase()).join('').replace(/[^a-zA-Z0-9]/g, '');

  const outDir  = isRust
    ? path.join(ROOT, 'content', 'rust_kernels', 'src')
    : path.join(ROOT, 'content', 'soma_kernel');
  const outFile = isRust
    ? path.join(outDir, `${slug}.rs`)
    : path.join(outDir, `${slug}.md`);

  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

  if (fs.existsSync(outFile)) {
    console.error(`\n  ✗ File already exists: ${outFile}\n`);
    process.exit(1);
  }

  // ── Write ─────────────────────────────────────────────────────────────────
  const content = isRust
    ? rustTemplate({ id, title: titleRaw, date, tags, structName })
    : markdownTemplate({ id, title: titleRaw, status: 'ACTIVE', type: 'kernel_doc', date, tags });

  fs.writeFileSync(outFile, content, 'utf8');

  // ── Report ────────────────────────────────────────────────────────────────
  console.log('\n  ✓ SYSTEM_KERNEL_LOG: scaffold complete');
  console.log(`    file:   ${path.relative(ROOT, outFile)}`);
  console.log(`    id:     ${id}`);
  console.log(`    type:   ${isRust ? 'rust (wasm-bindgen)' : 'kernel_doc (markdown)'}`);
  console.log(`    tags:   ${tags.join(', ')}`);
  if (isRust) {
    console.log(`    struct: ${structName}`);
    console.log(`\n  Next: add the struct to content/rust_kernels/src/lib.rs,`);
    console.log(`        then run: node scripts/import-rust.js`);
  } else {
    console.log(`\n  Next: run: npm run kernel:import  to ingest into the terminal.`);
  }
  console.log('');
}

main().catch(err => {
  console.error('  ✗ CLI error:', err.message);
  rl.close();
  process.exit(1);
});
