export function generateJsonLd(verdict) {
  const ld = {
    '@context': 'https://schema.org',
    '@type': 'Dataset',
    name: `Thermodynamic Audit Verdict: ${verdict.status}`,
    description: verdict.ruling,
    identifier: verdict.hash,
    dateCreated: verdict.timestamp,
    creator: {
      '@type': 'SoftwareApplication',
      name: 'scale94.com — The Open Ledger',
      url: 'https://scale94.com',
    },
    spatialCoverage: {
      '@type': 'Place',
      geo: {
        '@type': 'GeoCoordinates',
        latitude: verdict.coordinates.lat,
        longitude: verdict.coordinates.lon,
      },
    },
    variableMeasured: Object.entries(verdict.input || {})
      .filter(([k]) => ['temp', 'do', 'bod', 'dt', 'epi', 'nitrate', 'flow'].includes(k))
      .map(([k, v]) => ({ '@type': 'PropertyValue', name: k, value: v })),
    additionalProperty: [
      { '@type': 'PropertyValue', name: 'verdictStatus', value: verdict.status },
      { '@type': 'PropertyValue', name: 'dependency', value: verdict.dependency },
      { '@type': 'PropertyValue', name: 'kernelId', value: verdict.kernelId },
      { '@type': 'PropertyValue', name: 'sha256', value: verdict.hash },
    ],
  };
  return JSON.stringify(ld, null, 2);
}

export function generateEmbedHtml(verdict) {
  return `<div style="font-family:monospace;background:#0a0a0f;color:#cbd5e1;border:1px solid rgba(20,184,166,0.3);padding:16px;border-radius:4px;max-width:480px;">
  <div style="font-size:10px;text-transform:uppercase;letter-spacing:2px;color:#0d9488;margin-bottom:8px;">SCALE94 THERMODYNAMIC VERDICT</div>
  <div style="font-size:16px;font-weight:bold;color:${verdict.status === 'APPROVED' ? '#22c55e' : verdict.status === 'CONDITIONAL' ? '#eab308' : '#ef4444'};margin-bottom:8px;">${verdict.status}</div>
  <div style="font-size:11px;color:#64748b;margin-bottom:4px;">coordinates: ${verdict.coordinates.lat.toFixed(4)}, ${verdict.coordinates.lon.toFixed(4)}</div>
  <div style="font-size:11px;color:#64748b;margin-bottom:4px;">dependency: ${verdict.dependency}</div>
  <div style="font-size:10px;color:#475569;margin-bottom:8px;">hash: ${verdict.hash?.slice(0, 12)}...${verdict.hash?.slice(-8)}</div>
  <div style="font-size:11px;color:#94a3b8;border-top:1px solid rgba(20,184,166,0.15);padding-top:8px;">${verdict.ruling?.slice(0, 200)}${(verdict.ruling?.length ?? 0) > 200 ? '...' : ''}</div>
  <div style="font-size:9px;color:#334155;margin-top:8px;"><a href="https://scale94.com" style="color:#0d9488;">scale94.com</a> · The Open Ledger · ${verdict.timestamp?.slice(0, 10)}</div>
</div>`;
}

export async function generatePdf(verdict) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const m = 20;
  let y = m;

  doc.setFont('courier', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(13, 148, 136);
  doc.text('SCALE94.COM — THE OPEN LEDGER', m, y);
  y += 6;
  doc.text('THERMODYNAMIC AUDIT VERDICT', m, y);
  y += 10;

  doc.setFontSize(18);
  doc.setTextColor(verdict.status === 'APPROVED' ? 34 : 239, verdict.status === 'APPROVED' ? 197 : 68, verdict.status === 'APPROVED' ? 94 : 68);
  doc.text(verdict.status, m, y);
  y += 10;

  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  const lines = [
    `Hash: ${verdict.hash}`,
    `Timestamp: ${verdict.timestamp}`,
    `Coordinates: ${verdict.coordinates.lat.toFixed(4)}, ${verdict.coordinates.lon.toFixed(4)}`,
    `Dependency: ${verdict.dependency}`,
    `Kernel: ${verdict.kernelId}`,
    '',
    'INPUT PARAMETERS:',
    ...Object.entries(verdict.input || {})
      .filter(([k]) => ['temp', 'do', 'bod', 'dt', 'epi', 'nitrate', 'flow'].includes(k))
      .map(([k, v]) => `  ${k}: ${v}`),
    '',
    'RULING:',
    ...(verdict.ruling || '').split('\n'),
  ];

  for (const line of lines) {
    if (y > 270) { doc.addPage(); y = m; }
    doc.text(line, m, y);
    y += 4.5;
  }

  doc.setFontSize(7);
  doc.setTextColor(51, 65, 85);
  doc.text('Generated by scale94.com — The Open Ledger. This verdict is SHA-256 hashed and immutable.', m, 285);

  doc.save(`verdict-${verdict.hash?.slice(0, 12)}.pdf`);
}
